### ISSUE TITLE
CommandLine is not exposed /  Documentation not correct

### ISSUE THREAD

**Issue by RoelAdriaans** [hernantz/classyconf#3]
In the __init__.py the CommandLine loader and ClassyConf class are not exposed, making the CommandLine class not visible.

The documentation from the commandline example requires this https://classyconf.readthedocs.io/en/latest/loaders.html#commandline

Error:
```
>>> from classyconf import ClassyConf, Value, NOT_SET, CommandLine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ClassyConf' from 'classyconf' (/home/roel/python/lib/python3.9/site-packages/classyconf/__init__.py)
```

Tested with ClassyConf version 0.3.0

**Comment by hernantz** [comment]
Thanks for reporting this, I've issued a new relase `0.4.0` with the updated docs and exposing `CommandLine`

**Comment by RoelAdriaans** [comment]
Thanks for the quick updates! 
I will check it out tonight :)
